### ISSUE TITLE
Error: "Value was either too large or too small for an Int32 - 'open_interest'"

### ISSUE THREAD

**Issue by Onikiro** [tekr/DeribitDotNet#5]
Ticker entity has property OpenInterest with type int, that has too small size to deserialize data from deribit into the Ticker response. 

Full error message:
 Error processing message {"jsonrpc":"2.0","method":"subscription","params":{"channel":"ticker.BTC-PERPETUAL.raw","data":{"timestamp":1613222943860,"stats":{"volume_usd":193698960.0,"volume":4088.6392549,"price_change":-2.2837,"low":45250.0,"high":48624.5},"state":"open","settlement_price":47157.09,"open_interest":2446540246,"min_price":46191.37,"max_price":47598.22,"mark_price":46896.7,"last_price":46895.5,"instrument_name":"BTC-PERPETUAL","index_price":46881.37,"funding_8h":0.00052489,"estimated_delivery_price":46881.37,"current_funding":0.0,"best_bid_price":46898.0,"best_bid_amount":90.0,"best_ask_price":46898.5,"best_ask_amount":114580.0}}
Newtonsoft.Json.JsonReaderException: Could not convert to integer: 2446540246. Path 'open_interest'.
 ---> System.OverflowException: Value was either too large or too small for an Int32.

I'd like to make PR with this fix, could you review it?

**Comment by tekr** [comment]
Thanks Onikiro!
